### ISSUE TITLE
Bin reads from sample including any filters.

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#31]
Add a button to each sample panel to bin the reads currently displayed into a file or folder (also some way of doing this as a batch across all samples). Appropriate labelling of file.

**Comment by jameshadfield** [comment]
Talked to Luke about this and agree it's a valuable feature.

Currently the server, for each FASTQ, keeps lists of all the read positions & top mapping hit. We could have a UI where you could select:
* read length min & max (default: all)
* directory to write to
* tick which references you want so that only reads mapping to them are exported (default: all)

**Comment by rambaut** [comment]
This would be good. So the UI just sends a message back to the server which then spawns a process to do the binning?

**Comment by jameshadfield** [comment]
Exactly. The `nepal` branch deliberately shifts most "hard" things to the server, and now the client can just focus on visualisation -- meaning it feels faster. We could implement this now and then add in filtering as we implement it in the client.

**Comment by rambaut** [comment]
Closing this issue because this has been partially implemented.
